steps:
  # 1) Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/gcloudprj223/dotnetproject/webapp:${SHORT_SHA}'
      - '.'

  # 2) Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/gcloudprj223/dotnetproject/webapp:${SHORT_SHA}'

  # 3) Update GKE deployment to use new image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_CLUSTER_REGION}
        kubectl set image deployment/${_DEPLOYMENT_NAME} ${_CONTAINER_NAME}=asia-east1-docker.pkg.dev/gcloudprj223/dotnetproject/webapp:${SHORT_SHA} -n ${_NAMESPACE}
        kubectl rollout status deployment/${_DEPLOYMENT_NAME} -n ${_NAMESPACE}

substitutions:
  _CLUSTER_NAME: 'deployment-1-cluster'
  _CLUSTER_REGION: 'us-central1'
  _DEPLOYMENT_NAME: 'deployment-3'
  _CONTAINER_NAME: 'webapp3'
  _NAMESPACE: 'deploy-prj1'

images:
  - 'asia-east1-docker.pkg.dev/gcloudprj223/dotnetproject/webapp:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  # or, if you prefer:
  # logging: NONE

